Capture vaisseau
SpacerGamesEnterprise/Orion pull request #45
Opened 2023-05-09 14:01 UTC by Thelazerlog

2023-05-09 21:24 UTC, AsadPug approved these changes
epic changement good job 🚀 🪐 ⭐

2023-05-09 21:24 UTC, AsadPug commented on Orion_client/modeles/vaisseau.py
> +    def capturer(self, vaisseau_capturer: Vaisseau):
```suggestion
    def capturer(self, vaisseau_capturer: Vaisseau) -> bool:
```

2023-05-09 21:24 UTC, AsadPug commented on Orion_client/modeles/vaisseau.py
> +    def capturer(self, vaisseau_capturer: Vaisseau):
```suggestion
    def capturer(self, vaisseau_capturer: Vaisseau) -> bool:
```

2023-05-09 22:09 UTC, Grainus requested changes

2023-05-09 22:09 UTC, Grainus commented on Orion_client/modeles/vaisseau.py
> +        "Fonction qui permet de capturer un vaisseau"
``suggestion
        """Fonction qui permet de capturer un vaisseau."""
```

2023-05-09 22:09 UTC, Grainus commented on Orion_client/modeles/vaisseau.py
> +        else:
elif

2023-05-12 16:54 UTC, Grainus requested changes

2023-05-12 16:54 UTC, Grainus commented on Orion_client/command.py
> +        #Verifie la planete as un proprétaire si oui sa flotte devient flotte sinon elle est none
```suggestion
        # Si la planète a un propriétaire renvoi sa flotte, sinon None.
```

2023-05-12 16:54 UTC, Grainus commented on Orion_client/modeles/vaisseau.py
> +        """Fonction qui permet de capturer un vaisseau."""
```suggestion
        """Tente de capturer un vaisseau ennemi.
        Si self a deux fois plus de puissance que l'ennemi, le vaisseau 
        ennemi change de propriétaire. Sinon, self a 50% de chance
        d'être détruit.
        """
```

2023-05-12 16:54 UTC, Grainus commented on Orion_client/modeles/joueur.py
> +        "Fonction qui permet de changer de owner du vaisseau"
```suggestion
        """Rajoute le vaisseau capturé dans la flotte du joueur."""
```

2023-05-12 16:54 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +    def capturer(self, cible: Vaisseau):
```suggestion
    def capturer(self, cible: Vaisseau) -> None:
```

2023-05-12 16:54 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +            vaisseau.id
```suggestion
            vaisseau.id,
```

2023-05-12 16:54 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +                    self.capturer(self.controleur.modele._objects.objects[tags[1]])
```suggestion
            if tags and tags[0] != self.name:
                self.capturer(self.controleur.modele._objects.objects[tags[1]])
```

2023-05-12 16:54 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +    def capturer_etat(self,e):
```suggestion
    def capturer_etat(self):
```

2023-05-12 16:54 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +        hud.bouton_capturer.bind(b1, self.capturer_etat)
```suggestion
        hud.bouton_capturer.bind(b1, self.ignore_event(self.capturer_etat))
```

2023-05-12 16:54 UTC, Grainus commented on Orion_client/command.py
> +        except KeyError as e:
```suggestion
        except KeyError:
```

2023-05-12 17:02 UTC, Grainus approved these changes
Cool

2023-05-12 17:02 UTC, merged