Skill tree vue + modification modele skill_tree
SpacerGamesEnterprise/Orion pull request #47
Opened 2023-05-09 20:59 UTC by AsadPug

-ajout de la vue skill_tree
- le skill_tree est binded et lié dynamiquement avec le modele
- modification du modele pour débloquer les skills

2023-05-09 22:49 UTC, Grainus requested changes
Si tu veux faire from skill import *, tu doit absolument définir explicitement `__all__` dans le fichier de skills.

2023-05-09 22:49 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +from modeles.skill import *
Absolutely not.

2023-05-09 22:49 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +from modeles.skill import *
Mais bel effort pour un import dans la bonne section 👍

2023-05-09 22:49 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +        hud.bouton_skill_tree.bind(b1, self.ouvrir_skilltree)
???????

2023-05-09 22:49 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +    def ouvrir_skilltree(self, e: tk.Event) -> None:
Pourquoi prendre le event si pas utilisé?

2023-05-09 22:49 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +    def bind_buttons(self) -> None:
Documente tes fonctions.

2023-05-09 22:49 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +    def bind_skill_buttons(self) -> None:
Documente tes fonctions.

2023-05-09 22:49 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +    def debloque_skill(self, type: type[Skill]) -> None:
Documente tes fonctions.

2023-05-09 22:49 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +                    lambda event, type = skill_button.type_skill: self.debloque_skill(type)
self.ignore_event

2023-05-09 22:49 UTC, Grainus commented on Orion_client/graphics/boutons/skillNonDebloque.png
As-tu vraiment besoin d'une image aussi grosse ?

2023-05-09 22:49 UTC, Grainus commented on Orion_client/modeles/etoile.py
Good 👍

2023-05-09 22:49 UTC, Grainus commented on Orion_client/vues/asset_manager.py
> +        avatar_size = 154  # NOTE: Why is this here? ANSWER: was used before I resized each file individually
remove it then

2023-05-09 22:49 UTC, Grainus commented on Orion_client/vues/asset_manager.py
> +            "boutonRetour.png":bouton_size,
```suggestion
            "boutonRetour.png": bouton_size,
```

2023-05-09 22:49 UTC, Grainus commented on Orion_client/vues/skill_tree.py
> +from modeles.skill import *
No.

2023-05-09 22:49 UTC, Grainus commented on Orion_client/vues/skill_tree.py
> +        self.screen_size = Dimension2D(
poggers

2023-05-09 22:49 UTC, Grainus commented on Orion_client/vues/skill_tree.py
>  class VueSkillTree(Vue):
Documentation

2023-05-09 22:49 UTC, Grainus commented on Orion_client/vues/skill_tree.py
> +    def load_skill_button_list(self) -> None:
Documentation

2023-05-09 22:49 UTC, Grainus commented on Orion_client/vues/skill_tree.py
> +    def load_icone_path(self) -> None:
Documentation + 1 ligne entre méthodes

2023-05-09 22:49 UTC, Grainus commented on Orion_client/vues/skill_tree.py
> +    def show_skill_tree_lines(self) -> None:
Documentation

2023-05-09 22:49 UTC, Grainus commented on Orion_client/vues/skill_tree.py
> +    def update(self) -> None:
Documentation

2023-05-09 23:17 UTC, AsadPug commented on Orion_client/gestionnaire_vue.py
> +        hud.bouton_skill_tree.bind(b1, self.ouvrir_skilltree)
il faut faire ça parce que le gestionnaire skill tree prend l'Étoile en parametre. C'est litteralement toi qui m'a dit de faire ça lmao

2023-05-09 23:17 UTC, AsadPug commented on Orion_client/gestionnaire_vue.py
> +    def ouvrir_skilltree(self, e: tk.Event) -> None:
sinon ya une errreur dans tkinter

2023-05-09 23:18 UTC, AsadPug commented on Orion_client/gestionnaire_vue.py
> +    def bind_buttons(self) -> None:
si jai le temps, le client voit pas les docu xd

2023-05-09 23:18 UTC, AsadPug commented on Orion_client/gestionnaire_vue.py
> +    def bind_skill_buttons(self) -> None:
le client ne lit pas la docu, les personnes séniles dans les maisons de retraite non plus

2023-05-09 23:19 UTC, AsadPug commented on Orion_client/vues/skill_tree.py
>  class VueSkillTree(Vue):
🧓

2023-05-09 23:20 UTC, AsadPug commented on Orion_client/vues/skill_tree.py
> +    def update(self) -> None:
un jour jvais les faire (jamais acause le cours finni dans 2 semaines et jean marc sen calisse)

2023-05-09 23:31 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +        hud.bouton_skill_tree.bind(b1, self.ouvrir_skilltree)
```suggestion
        hud.bouton_skill_tree.bind(b1, self.ignore_event(self.ouvrir_skilltree))
```

2023-05-09 23:33 UTC, AsadPug commented on Orion_client/vues/asset_manager.py
> +        avatar_size = 154  # NOTE: Why is this here? ANSWER: was used before I resized each file individually
yess ofc jvoulais juste que tu vois le note lol

2023-05-09 23:36 UTC, Grainus commented on Orion_client/gestionnaire_vue.py
> +    def ouvrir_skilltree(self, e: tk.Event) -> None:
```suggestion
    def ouvrir_skilltree(self) -> None:
```

2023-05-15 13:23 UTC, Grainus commented on Orion_client/modeles/skill.py
> +]
```suggestion
    TransmissionQuantique,
]

```

2023-05-15 13:25 UTC, Grainus approved these changes

2023-05-15 13:29 UTC, merged